name: flutter_habit_run
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0
  shared_preferences: ^2.0.6
  http: ^0.13.3
  dio: ^4.0.0
  json_annotation: ^4.0.1
  connectivity: ^3.0.6
  flutter_secure_storage: 3.3.5

  flutter_bloc: 6.1.1
  meta: ^1.2.4
  equatable: 1.2.5
  responsive_framework: ^0.0.14
  data_connection_checker: ^0.3.4
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  location: ^4.3.0
  flutter_polyline_points: ^0.2.1
  spring: ^2.0.2
  permission_handler: ^8.1.0
  pedometer: ^3.0.0
  graphql: ^5.0.0
  sentry_flutter: ^5.1.0
  webview_flutter: ^2.0.9
  google_mobile_ads: ^0.13.2
  awesome_notifications: 0.0.6
  assets_audio_player: ^3.0.3+3
  flutter_tts: ^3.2.1
  home_widget: ^0.1.3
  flutter_local_notifications: ^8.1.1
  awesome_dialog: ^2.1.0
  share_plus: ^2.1.4
  path_provider: ^2.0.2
  flutter_email_sender: ^5.0.2
  flutter_slidable: ^0.6.0
  
  #login google
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_auth: ^1.4.1
  flutter_facebook_auth: ^3.5.1
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  in_app_purchase: ^1.0.8

  #camera
  camera: ^0.8.1+7
  gallery_saver: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
  json_serializable: 4.1.3
  build_runner:
  pedantic: null
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.0
  logger:
  effective_dart: ^1.3.0

# For information on the generic Dart part of this file, see the
# following ui: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/badges/
    - sounds/
    - assets/images/
    - gif/
    - images/style_map/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/FontsFree-Net-SFProDisplay-Bold.ttf
        - asset: fonts/FontsFree-Net-SFProDisplay-Medium.ttf
        - asset: fonts/FontsFree-Net-SFProDisplay-Regular.ttf
    - family: Futura
      fonts:
        - asset: fonts/Futura Bold Italic font.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: FugazOne
      fonts:
        - asset: fonts/FugazOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-BoldItalic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: s # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en

flutter_native_splash:
  image: assets/icons/dh_logo.png
  color: "FFFFFF"
  android_disable_fullscreen: true

flutter_icons:
  image_path: "images/logo@3x.png"
  android: true
  ios: true

#flutter pub run flutter_rename_app
include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    - "lib/presentation/localization/**"
  errors:
    missing_required_param: error
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
