on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
#       - run: flutter pub get
# #      - run: flutter test
#       - run: flutter build apk
#       - name: Create a Release APK
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "build/app/outputs/flutter-apk/app.apk"
# #          token: ${{ secrets.TOKEN }}
#           commit: version-5
#           tag: v5.0.${{ github.run_number }}
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: anhdung2881999@gmail.com
          # Required sender full name (address can be skipped):
          from: Lê Anh Dũng
          # Optional plain body:
          body: "Version v5.1.4
                  - update group
                  - update login facebook
                  - link: https://drive.google.com/drive/u/0/folders/1qoupwbBRqxQQZbMsKVmR--UvDZe9hegy"
        # Upload to Drive
      - name: Upload Folder to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: runner-habit-20210927
          credentials: secrets.<YOUR_DRIVE_CREDENTIALS>
          folder: 1qoupwbBRqxQQZbMsKVmR--UvDZe9hegy